# Generated by Django 4.2.17 on 2026-02-04 10:12

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0116_fix_dynamic_group_group_type_data_migration'),
        ('dcim', '0062_module_data_migration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='other', max_length=50)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('compatible_device_types', models.ManyToManyField(blank=True, related_name='compatible_spare_parts', to='dcim.devicetype')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_part_types', to='dcim.manufacturer')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Spare Part Type',
                'verbose_name_plural': 'Spare Part Types',
                'ordering': ['category', 'manufacturer', 'name'],
                'unique_together': {('manufacturer', 'part_number')},
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SparePartInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('minimum_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_quantity', models.PositiveIntegerField(default=0)),
                ('storage_location_detail', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_part_inventories', to='dcim.location')),
                ('spare_part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='nautobot_spare_parts.spareparttype')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Spare Part Inventory',
                'verbose_name_plural': 'Spare Part Inventories',
                'ordering': ['location', 'spare_part_type'],
                'unique_together': {('spare_part_type', 'location')},
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SparePartTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('related_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_part_transactions', to='dcim.device')),
                ('spare_part_inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='nautobot_spare_parts.sparepartinventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_part_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spare Part Transaction',
                'verbose_name_plural': 'Spare Part Transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['spare_part_inventory', 'timestamp'], name='nautobot_sp_spare_p_249e3c_idx'), models.Index(fields=['transaction_type'], name='nautobot_sp_transac_ae81bb_idx')],
            },
        ),
    ]
