# Generated by Django 4.2.30 on 2026-09-07 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_spare_parts', '0003_add_field_validators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepartinventory',
            options={'ordering': ['location__name', 'spare_part_type__name'], 'verbose_name': 'Spare Part Inventory', 'verbose_name_plural': 'Spare Part Inventories'},
        ),
        migrations.AlterModelOptions(
            name='spareparttype',
            options={'ordering': ['category', 'manufacturer__name', 'name'], 'verbose_name': 'Spare Part Type', 'verbose_name_plural': 'Spare Part Types'},
        ),
        migrations.RemoveIndex(
            model_name='spareparttransaction',
            name='nautobot_sp_spare_p_249e3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='spareparttransaction',
            name='nautobot_sp_transac_ae81bb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='spareparttype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='spareparttransaction',
            name='transfer_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='spareparttransaction',
            name='request_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='spareparttransaction',
            name='reserved_after',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spareparttransaction',
            name='reserved_before',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spareparttransaction',
            name='reserved_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spareparttransaction',
            name='jira_ticket',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Jira ticket must look like INFRA2-1234.', regex='^[A-Z][A-Z0-9]*-\\d+$')]),
        ),
        migrations.AlterField(
            model_name='spareparttransaction',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spareparttransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='spareparttransaction',
            name='transaction_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='spareparttype',
            name='category',
            field=models.CharField(db_index=True, default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='spareparttype',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spareparttype',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='spareparttransaction',
            index=models.Index(fields=['spare_part_inventory', '-timestamp'], name='nautobot_sp_spare_p_d83a23_idx'),
        ),
        migrations.AddIndex(
            model_name='spareparttransaction',
            index=models.Index(fields=['transaction_type', '-timestamp'], name='nautobot_sp_transac_df4592_idx'),
        ),
        migrations.AddConstraint(
            model_name='sparepartinventory',
            constraint=models.CheckConstraint(check=models.Q(('quantity_reserved__lte', models.F('quantity_on_hand'))), name='spare_parts_reserved_lte_on_hand'),
        ),
        migrations.AddConstraint(
            model_name='spareparttype',
            constraint=models.UniqueConstraint(condition=models.Q(('part_number', ''), _negated=True), fields=('manufacturer', 'part_number'), name='spare_parts_unique_manufacturer_part_number'),
        ),
        migrations.RemoveField(
            model_name='spareparttype',
            name='slug',
        ),
    ]
