# Generated by Django 5.2.14 on 2026-10-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_spare_parts", "0005_backfill_reserved_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="spareparttransaction",
            name="failure_reason",
            field=models.CharField(blank=True, db_index=True, default="", max_length=50),
        ),
    ]
